<?php

namespace AppBundle\Repository;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends \Doctrine\ORM\EntityRepository
{
}
